### ISSUE TITLE
We should merge debian/ instead of replace debian/

### ISSUE THREAD

**Issue by alee-cd** [gardenlinux/backup_package-build#14]
**What would you like to be added**:

Replicate a very clever design from our current GitLab pipeline that merge `debian/` instead of replace `debian/`.

**Why is this needed**:

Debian package build requires all the necessary `debian/` files available. We have to provide them by our own If we want to replace `debian/` in source package build.

In our current GitLab pipeline, we provide separate `patches/` and `debian/` folders, as demonstrated in the following GitLab pipeline: https://gitlab.com/gardenlinux/gardenlinux-package-aws-kms-pkcs11.

The GitLab pipeline uses the provided patches from `patches/` folder to update the upstream source tree. And merge `debian/` with `rsync` method which is only triggered if the provided `debian/` folder exists. Additionally, to avoid any race conditions, the patches are only applied from the `patches/` folder rather than the `debian/patches` folder.

**Comment by nanory** [comment]
Hi everyone,

we had an internal discussion about this issue and we decided that we will stick with the replacement instead of merging the `debian/` directory due to the following things:
* This way, we only do the replacement if we really want to overwrite the whole packaging behavior of the original package and don't get unintended changes into our package builds.
* If we really just want to modify some parts of the original `debian/` folder, we could just modify some of the packages files (e.g. `debian/rules`) by patching them. This way, we rely on whatever Debian defines for their packages but we can put some sprinkles on top of them, if we need to do so.

As a result, we stick to the current implementation and therefore don't need the suggested change here.
